version: '2'
services:
    web:
        # image: mxr576/stanbol
        build: ./docker/stanbol
        container_name: stanbol
        ports:
            - 9988:8080
        environment:
              - VIRTUAL_HOST=stanbol.sobol.nr
        network_mode: "bridge"


